name: Kubescape Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kubescape
        run: |
          curl -sL https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh -o install.sh
          chmod +x install.sh
          sudo ./install.sh
          sudo mv kubescape /usr/local/bin/
          kubescape version

      - name: Scan Kubernetes YAML files
        run: |
          kubescape scan framework nsa --format pretty --output results.txt **/*.yaml || true

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-nsa-results
          path: results.txt
